### PR TITLE
fix for electronickit is not used when trying to prisonbreak

### PR DESCRIPTION
**Pull request by abu3baid**
**Describe Pull request**
Sorry if i am not following the guidelines, but this is how I fixed not being able to use electronickit item when prison breaking.
it wasn't work, at least for me.

**Questions:**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? No
- Does your code fit the style guidelines? I don't know
- Does your PR fit the contribution guidelines? I don't know

### CODE REVIEW

**Comment by Sharkiiie** [comment]
iirc the electronickit is already made a usable item in smallresources

**Comment by abu3baid** [comment]
> iirc the electronickit is already made a usable item in smallresources

Oh, didn't know about that, can you show me where? please? thanks.

**Comment by Sharkiiie** [comment]
I was mistaken.
It's in [bankrobbery](https://github.com/qbcore-framework/qb-bankrobbery/blob/main/server/main.lua#L441)

**Comment by abu3baid** [comment]
> I was mistaken. It's in [bankrobbery](https://github.com/qbcore-framework/qb-bankrobbery/blob/main/server/main.lua#L441)

Oh, I see. that's why it's not usable for me, i don't use this script :)
Anyway, thanks for making it clear for me.

**Pull request closed without merging**
