### PR TITLE
Added qb-target and polyzone and removed Drawtext3D

### PR DESCRIPTION
**Pull request by amantu-qbit**

### CODE REVIEW

**Comment by ItsANoBrainer** [comment]
Instead of Creating a ped and then creating a box around it, use `AddTargetEntity` from qb-target and pass the ped entity id as the target and then targeting the ped will be proper. Right now its kinda janky and hard to target.

**Comment by amantu-qbit** [comment]
@ItsANoBrainer @BerkieBb @IdrisDose Can you check?

**Comment by BerkieBb** [comment]
You can also request a review from us via the `Reviewers` tab on the right, you can press the gear icon to the right of `Reviewers` and select us, just a tip for the next time

**Comment by BerkieBb** [comment]
Updated my original review

**Comment by waseem-h** [comment]
@amantu-qbit Seems like nothing got added to the main branch as a result of the merge. The commits are just gone

**Comment by BerkieBb** [comment]
Because he reverted all the changes in the last commit of his pull request

**Comment by amantu-qbit** [comment]
What?

**Comment by BerkieBb** [comment]
Your 'small fixes' commit actually reverted all changes

**Comment by amantu-qbit** [comment]
@BerkieBb IDK how that happened. I'm creating new PR with the hcanged

**Comment by amantu-qbit** [comment]
@BerkieBb added back again on PR #66

**Pull request merged**
