### PR TITLE
add counter to DrawText3D

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by evanillaa** [comment]
https://imgur.com/a/yB33wmw
@GhzGarage

**Comment by zfbx** [comment]
I would adjust this slightly.. maybe to be more like this:
```lua
if jailTime > 1 then
    DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, 'Waiting: ~g~'..jailTime.. ' months remaining')
elseif jailTime > 0 then
    DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, 'Waiting: ~g~1 month left!')
else
    DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, "Time's up!")
end
```

**Comment by FreakOutModz** [comment]
> I would adjust this slightly.. maybe to be more like this:
> 
> ```lua
> if jailTime > 1 then
>     DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, 'Waiting: ~g~'..jailTime.. ' months remaining')
> elseif jailTime > 0 then
>     DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, 'Waiting: ~g~1 month left!')
> else
>     DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, "Time's up!")
> end
> ```

That is not correct. Adding a check to `elseif jailTime > 0 then` is not necessary. Correct answer should be:

```lua
if jailTime > 1 then
    DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, jailTime..' months left to sentence')
elseif jailTime == 0 then
    DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, "~g~Time is over!")
end
```

With `else`, you will run the script for everyone, even those without any time. Think about optimization for the player in the client.

**Comment by zfbx** [comment]
> That is not correct. Adding a check to `elseif jailTime > 0 then` is not necessary. Correct answer should be:
> 
> ```lua
> if jailTime > 1 then
>     DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, jailTime..' months left to sentence')
> elseif jailTime == 0 then
>     DrawText3D(Config.Locations["freedom"].coords.x, Config.Locations["freedom"].coords.y, Config.Locations["freedom"].coords.z, "~g~Time is over!")
> end
> ```
> 
> With `else`, you will run the script for everyone, even those without any time. Think about optimization for the player in the client.

Actually, no, there's an if statement further up that stops the whole thing from running if you're not in jail. And the reason I added the > 0 was to have a separate message for when there's 1 "month" left vs the many "months" that would be 2 or greater

**Comment by FreakOutModz** [comment]
Well having `1 months` and less code is way better then adding a check for this.

**Comment by zfbx** [comment]
> Well having `1 months` and less code is way better then adding a check for this.

I disagree, considering this is such a user facing function that anyone in prison will use and most will be keeping track of just how much time is left, having that little extra message of `1 month left!` is a nice little Easter egg of encouragement.

**Comment by BerkieBb** [comment]
> Well having `1 months` and less code is way better then adding a check for this.

It's not like you're going to notice anything performance wise with those checks as it's just an if statement checking a set local variable

**Pull request closed without merging**
