### PR TITLE
fix(client/main): use config for ped coords

### PR DESCRIPTION
**Pull request by BerkieBb**
**Describe Pull request**
This fixes the issue of #75 not changing the coords of the peds whenever the config of it is changed

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by Andyauk** [comment]
a few changes, as the peds are not right.

    ["freedom"] = {
        coords = vector4(1836.36, 2585.33, 44.86, 85.43)
    },

    ["shop"] = {
        coords = vector4(1786.19, 2557.77, 44.62, 181.35)
    },

I'm not sure about middle. as that is from the paid version on the prison qb uses. so maybe change it to 

    ["middle"] = {
        coords = vector4(1760.31, 2489.46, 45.84, 123.35)
    },

that places it inside the cells. and maybe a blip for the cell room, thanks

**Comment by Andyauk** [comment]
> > a few changes, as the peds are not right. floating in the air lol
> 
> Just lower the Z by one

yes, i was just sending the updated coods. 
i feel the prison and the doorlocks were not made for the same mlo.

**Comment by BerkieBb** [comment]
All coords should be good now

**Comment by BerkieBb** [comment]
The middle coord is for the exact middle point of the jail to check if someone escaped or not with a distance check of 200 GTA units, the yard is fine as is

**Pull request merged**
